### ISSUE TITLE
many errors in logs KeyError: 'is_tentative'

### ISSUE THREAD

**Issue by jacekpaszkowski** [djtimca/HASpaceX#17]
I have many arror in logs

```
2020-11-22 15:50:13 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 158, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/spacex/binary_sensor.py", line 144, in is_on
    if launch_data["is_tentative"] is True:
KeyError: 'is_tentative'
```

**Comment by poudenes** [comment]
I have the same on HA 0.118.2

**Comment by djtimca** [comment]
Same issue as #16
