### ISSUE TITLE
Error doing job: Task exception was never retrieved Traceback (most recent call last):

### ISSUE THREAD

**Issue by pmrosa** [djtimca/HASpaceX#21]
Hi there,

I've been having this error clogging the error log (intervals less than a minute):

```
2020-12-12 00:10:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/spacex/sensor.py", line 404, in device_state_attributes
    self.attrs["fairings_reused"] = latest_launch_data["fairings"].get(
AttributeError: 'NoneType' object has no attribute 'get'
```

Thanks.
Pedro.

**Comment by djtimca** [comment]
This was fixed in the latest update. Please check the HACS page for an update to your system.
