### ISSUE TITLE
The "Next Launch Rocket" is not currently available.

### ISSUE THREAD

**Issue by pixelsquared** [djtimca/HASpaceX#25]
The "Next Launch Rocket" (sensor.next_launch_rocket) sensor says "This entity is not currently available.".

![Screenshot from 2021-01-25 13-31-21](https://user-images.githubusercontent.com/10050016/105755992-a73fef80-5f11-11eb-8ef9-d95c07ef37ea.png)

**Comment by pixelsquared** [comment]
Not sure if this error message is related but I see this in the HA logs.

```
2021-01-25 12:56:30 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
await self.async_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
attr.update(self.device_state_attributes or {})
File "/config/custom_components/spacex/sensor.py", line 330, in device_state_attributes
self.attrs["core_" + str(core_counter) + "_serial"] = this_core.get(
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by pixelsquared** [comment]
Thanks!
