### ISSUE TITLE
Index Out of Range

### ISSUE THREAD

**Issue by adam-olson** [djtimca/HASpaceX#45]
Looks like we have and Index out of range.

'2022-07-07 18:30:39 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/spacex/sensor.py", line 590, in state
    self._state = latest_launch_data["payloads_detail"][0]["name"]
IndexError: list index out of range'

**Comment by djtimca** [comment]
Fixed and will be released to HACS shortly.
