### ISSUE TITLE
Entities list as unavailable

### ISSUE THREAD

**Issue by pmrosa** [djtimca/HASpaceX#9]
I installed the add-on today and all entities are showing unavailable.

**Comment by adam-olson** [comment]
The log shows an error that keeps repeating every 30 seconds to a minute, 

2020-10-25 12:46:44 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 118, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 192, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/spacex/binary_sensor.py", line 120, in device_state_attributes
    self.attrs["last_updated"] = launch_data["last_date_update"]
KeyError: 'last_date_update'

**Comment by pmrosa** [comment]
Same... but I installed it today so I don't know if it's a new problem.

2020-10-25 17:08:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 118, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 192, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/spacex/binary_sensor.py", line 120, in device_state_attributes
    self.attrs["last_updated"] = launch_data["last_date_update"]
KeyError: 'last_date_update'

**Comment by sansillusion** [comment]
Same problem, used to work good but started to fail last night

**Comment by djtimca** [comment]
Fixed with latest release 020 - change in SpaceX data caused issues.
